{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "rsi-common-libraries",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rsi-common-libraries-0.0.19-plain.jar",
          "url": "rsi-common-libraries-0.0.19-plain.jar",
          "size": 178688,
          "sha512": "d4f8e20540750b859ed3fdf66f96330e131da781f01cd11dea119805bc9ac06db0cc716aa688ee3c9e79faae77393fff494a1b059d400d51f42ff25eaf69b73c",
          "sha256": "7bb39dad044d15a11c2b7daf4377223adf2e34505c351e28eb30284a24bbbf0c",
          "sha1": "1ca27fbf8e7978fd025bd7cc557cc6507181eb10",
          "md5": "f3617f96d5de252e263f68193dababe9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.19.0-rc2"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "common-libraries",
          "version": {
            "requires": "0.0.674"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsi-common-libraries-0.0.19-plain.jar",
          "url": "rsi-common-libraries-0.0.19-plain.jar",
          "size": 178688,
          "sha512": "d4f8e20540750b859ed3fdf66f96330e131da781f01cd11dea119805bc9ac06db0cc716aa688ee3c9e79faae77393fff494a1b059d400d51f42ff25eaf69b73c",
          "sha256": "7bb39dad044d15a11c2b7daf4377223adf2e34505c351e28eb30284a24bbbf0c",
          "sha1": "1ca27fbf8e7978fd025bd7cc557cc6507181eb10",
          "md5": "f3617f96d5de252e263f68193dababe9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsi-common-libraries-0.0.19-sources.jar",
          "url": "rsi-common-libraries-0.0.19-sources.jar",
          "size": 41649,
          "sha512": "ad0ed05d65bc377da3871d591cd12e3e7a9aff9528463ef28a1c52d408144a5b39a40396c11107697133b98abdd497a6b2aeca0aa43270df0c2efdd1155d92dc",
          "sha256": "ee49ba9c73a73b2fb895c8e374ddfc993ca910b5db16cb591703bff8c0358274",
          "sha1": "5bc0db548a6bf935fa530195a46a1189d3d02483",
          "md5": "8a51a137226ab1eac94982d9a362f090"
        }
      ]
    }
  ]
}
