{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "common-libraries",
    "version": "0.0.696",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-libraries-0.0.696-plain.jar",
          "url": "common-libraries-0.0.696-plain.jar",
          "size": 4297068,
          "sha512": "2d64f7a07b7005235ba8316d559d317fa4fa0ba8520b6782ce679e84fd1b0e9b173b1209240d63ae9a41f8a1c171db29a9a262a3878de2e13c866dc00cc27517",
          "sha256": "fcca21454adf25046d626bc096fb57ef6b2ccdb1614883a48d04219610a20b40",
          "sha1": "ca93acf8c593504ab1b750d3c0604a132977f505",
          "md5": "361480dc3ab2d876e95d250cf77a49a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.sf.barcode4j",
          "module": "barcode4j",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "77.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.6"
          }
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-libraries-0.0.696-plain.jar",
          "url": "common-libraries-0.0.696-plain.jar",
          "size": 4297068,
          "sha512": "2d64f7a07b7005235ba8316d559d317fa4fa0ba8520b6782ce679e84fd1b0e9b173b1209240d63ae9a41f8a1c171db29a9a262a3878de2e13c866dc00cc27517",
          "sha256": "fcca21454adf25046d626bc096fb57ef6b2ccdb1614883a48d04219610a20b40",
          "sha1": "ca93acf8c593504ab1b750d3c0604a132977f505",
          "md5": "361480dc3ab2d876e95d250cf77a49a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-libraries-0.0.696-sources.jar",
          "url": "common-libraries-0.0.696-sources.jar",
          "size": 1450376,
          "sha512": "a086699c482558bb9630659785152846871d9cacc35dc5f1e28bb73d0242fe946ea8f9ee597ae43ed143db8e8bae4b0b9d58d15c3fbc955aa9be890c05ac9e32",
          "sha256": "a3656816722bd44bdda5521ea839c33663a66d5507c2ffb64159bd3f35c022fc",
          "sha1": "16614ac5d672f4c6a27078089afaf9e9ed64603c",
          "md5": "219565cad27f38c2a5719d25cf14fe15"
        }
      ]
    }
  ]
}
