{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "common-libraries",
    "version": "0.0.671",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-libraries-0.0.671-plain.jar",
          "url": "common-libraries-0.0.671-plain.jar",
          "size": 4121199,
          "sha512": "fafffd668cbb797ddd9fb043ffc2b86971e4bad0a5631678e95bf05a99fd9861deaf0ef1a1a851476ff0040112eabdc7d3afa7607026e240e29b0ab50bfaee69",
          "sha256": "11563470865372c791516387fe74b6fc986b66f4f4a7b7d0b9e766af60ad325a",
          "sha1": "8850686d83873f8d6231d4565482311ffb2f0f92",
          "md5": "2247e6ea9628c6894d356556fc4a2907"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.sf.barcode4j",
          "module": "barcode4j",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "77.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.6"
          }
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-libraries-0.0.671-plain.jar",
          "url": "common-libraries-0.0.671-plain.jar",
          "size": 4121199,
          "sha512": "fafffd668cbb797ddd9fb043ffc2b86971e4bad0a5631678e95bf05a99fd9861deaf0ef1a1a851476ff0040112eabdc7d3afa7607026e240e29b0ab50bfaee69",
          "sha256": "11563470865372c791516387fe74b6fc986b66f4f4a7b7d0b9e766af60ad325a",
          "sha1": "8850686d83873f8d6231d4565482311ffb2f0f92",
          "md5": "2247e6ea9628c6894d356556fc4a2907"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-libraries-0.0.671-sources.jar",
          "url": "common-libraries-0.0.671-sources.jar",
          "size": 1394012,
          "sha512": "93e0e1ded693cbd09eb8af33ffe1ed007bd5c098fc2d3692b3de6356f39301e698da1dc74d001c31b938cc07246c135e7c33268b0d254060046d48eeb6c7ccca",
          "sha256": "114bb79d867d4e57f39251eacb29369c9e7f624636e3c5e2a7d199a0e3710177",
          "sha1": "52ca844178f03ef76c6b19cc27b4e4d49635c728",
          "md5": "339ceda45914cc24109bcd474bbf77a4"
        }
      ]
    }
  ]
}
