{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "common-libraries",
    "version": "0.0.669",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-libraries-0.0.669-plain.jar",
          "url": "common-libraries-0.0.669-plain.jar",
          "size": 4121202,
          "sha512": "1be4b38879d348435e5f4047d936caa7d56a8ba039ef143e07725b7148f2e4be9e60fc55c79b51ea2878fe2ed3dc9fd54faf9383bd3a1025e6839ccd87e5ff99",
          "sha256": "16a43d7aaf80839c1cf6fb6ce2728be91a52381d23fe177fb7fccd5566ce2434",
          "sha1": "e45293f6c4bf536f7e0aa515cc6da222f1d7b34a",
          "md5": "7659acb78320259ad29402dcdc9d6915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.sf.barcode4j",
          "module": "barcode4j",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "77.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.6"
          }
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-libraries-0.0.669-plain.jar",
          "url": "common-libraries-0.0.669-plain.jar",
          "size": 4121202,
          "sha512": "1be4b38879d348435e5f4047d936caa7d56a8ba039ef143e07725b7148f2e4be9e60fc55c79b51ea2878fe2ed3dc9fd54faf9383bd3a1025e6839ccd87e5ff99",
          "sha256": "16a43d7aaf80839c1cf6fb6ce2728be91a52381d23fe177fb7fccd5566ce2434",
          "sha1": "e45293f6c4bf536f7e0aa515cc6da222f1d7b34a",
          "md5": "7659acb78320259ad29402dcdc9d6915"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-libraries-0.0.669-sources.jar",
          "url": "common-libraries-0.0.669-sources.jar",
          "size": 1394007,
          "sha512": "e989f237685c3bdd3919a252425fd6458b74b1f9c9beb4546af95121124f7c0347db835f9d586d473ff6630846a1e063f72ce0049333c971462789022f6c60aa",
          "sha256": "5c357644f86d90662bac8a717f7ee9f49dbbc847695f3cd53d50ca99090e8446",
          "sha1": "d8222aa9f61de3612702a38725ac722318eab5f6",
          "md5": "883baf3a5d388ed7f7a9580fe9244384"
        }
      ]
    }
  ]
}
