{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "rsi-common-libraries",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "rsi-common-libraries-0.0.21-plain.jar",
          "url": "rsi-common-libraries-0.0.21-plain.jar",
          "size": 178833,
          "sha512": "f76d700e480ce0d195479d67c0870ddd58775ec2072c712946b85e0aa6d8050170e3717e7706b6af9ab3086a9a1a0f1137b6511987ce1b5e4670c0bf228bd949",
          "sha256": "584820803652a962c9d0275d17e930f06224f5528901b93f6e5caaa7727f231a",
          "sha1": "adec734c06808d0fa19ce59621cf77f63953a60f",
          "md5": "a92225780b2e2f73a5748d02541e8f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.19.0-rc2"
          }
        },
        {
          "group": "jp.co.ricoh.cotos",
          "module": "common-libraries",
          "version": {
            "requires": "0.0.674"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "rsi-common-libraries-0.0.21-plain.jar",
          "url": "rsi-common-libraries-0.0.21-plain.jar",
          "size": 178833,
          "sha512": "f76d700e480ce0d195479d67c0870ddd58775ec2072c712946b85e0aa6d8050170e3717e7706b6af9ab3086a9a1a0f1137b6511987ce1b5e4670c0bf228bd949",
          "sha256": "584820803652a962c9d0275d17e930f06224f5528901b93f6e5caaa7727f231a",
          "sha1": "adec734c06808d0fa19ce59621cf77f63953a60f",
          "md5": "a92225780b2e2f73a5748d02541e8f5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rsi-common-libraries-0.0.21-sources.jar",
          "url": "rsi-common-libraries-0.0.21-sources.jar",
          "size": 41661,
          "sha512": "6a04dc8999de0657473986b08f9af6fce5cedc0d985580b476da59f7418db6af7bb87733084cab482cb2b8e8cfe0e9c4fb263fc985b16fa6cbf9c0a8c7c1c1ef",
          "sha256": "216644c013f8ec4e0a148559afdd7cadb01ef9fc23f566569b9f7cf780a1dbd8",
          "sha1": "a2375d26b1bac40613e61ae289c0bc413117355f",
          "md5": "ceb8361512631ad968d5758d608fd80c"
        }
      ]
    }
  ]
}
