{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.ricoh.cotos",
    "module": "common-libraries",
    "version": "0.0.674",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-libraries-0.0.674-plain.jar",
          "url": "common-libraries-0.0.674-plain.jar",
          "size": 4121604,
          "sha512": "66509a7fea2bcc2bca94f937ece3a72a11cb413f05425bb6920df7945f2c726b45b2a40d8d1110ecbd56e658fc3b8ea523e4771763cbc5026e91574eaeb4004e",
          "sha256": "778c6bddf2ee8f92421ad74bb49e73bbfe3b6a565ae47658c7072e33b3bc7874",
          "sha1": "8ba600e0fb25ffd8757e7145d12d4704962a8f90",
          "md5": "a9f5bba839f3f956301d8fd4684a418e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-mail",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "com.github.spullara.mustache.java",
          "module": "compiler",
          "version": {
            "requires": "0.9.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "8.0.2.Final"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.2.5.Final"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jxls",
          "module": "jxls-poi",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi",
          "version": {
            "requires": "3.17"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "io.swagger",
          "module": "swagger-core",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "commons-beanutils",
          "module": "commons-beanutils",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "wsdl4j",
          "module": "wsdl4j",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "net.sf.barcode4j",
          "module": "barcode4j",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "77.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.17.5"
          }
        },
        {
          "group": "com.oracle.database.jdbc",
          "module": "ojdbc8",
          "version": {
            "requires": "23.7.0.25.01"
          }
        },
        {
          "group": "org.openjdk.nashorn",
          "module": "nashorn-core",
          "version": {
            "requires": "15.6"
          }
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "javax.xml.soap",
          "module": "javax.xml.soap-api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-libraries-0.0.674-plain.jar",
          "url": "common-libraries-0.0.674-plain.jar",
          "size": 4121604,
          "sha512": "66509a7fea2bcc2bca94f937ece3a72a11cb413f05425bb6920df7945f2c726b45b2a40d8d1110ecbd56e658fc3b8ea523e4771763cbc5026e91574eaeb4004e",
          "sha256": "778c6bddf2ee8f92421ad74bb49e73bbfe3b6a565ae47658c7072e33b3bc7874",
          "sha1": "8ba600e0fb25ffd8757e7145d12d4704962a8f90",
          "md5": "a9f5bba839f3f956301d8fd4684a418e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-libraries-0.0.674-sources.jar",
          "url": "common-libraries-0.0.674-sources.jar",
          "size": 1394334,
          "sha512": "5387071b23bf87ff6bb7ca0c3469cda692d8d8bf72ce5beb6994eb3a69cbd059db68aa27a8c4dfa0de940b277cd32c9f8c4abbc6ee32ba32a522b552403a088c",
          "sha256": "9fc59121d9a35ac85a88c96050aa2bd851bd31b14b978e3fe3dbb22d8bc0e815",
          "sha1": "b5dabe80ae42c5a9d9239b1168ec9e7c0f62fe90",
          "md5": "c25b6b67c3441ea9d1644e8980be53ed"
        }
      ]
    }
  ]
}
